language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn coveralls
  - yarn build-storybook
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search  